### PR TITLE
Remove phone login

### PR DESCRIPTION
**Pull request by cp-ishita-g**
- [x] remove phone login
- [x] remove phone details from profile screen

Simulator Screenshot - iPhone 15 Pro - 2024-10-07 at 11 48 38 Simulator Screenshot - iPhone 15 Pro - 2024-10-07 at 12 12 02

## Summary by CodeRabbit

- **New Features**
	- Removed phone sign-in option and related UI elements, streamlining the authentication process.
  
- **Bug Fixes**
	- Addressed issues related to phone number input and verification, enhancing user experience during sign-in.

- **Documentation**
	- Updated localization files to reflect the removal of phone-related strings.

- **Chores**
	- Cleaned up code by removing unused imports and methods related to phone sign-in functionality. 

These changes indicate a shift towards alternative authentication methods, enhancing overall user experience.

### CODE REVIEW

**Comment by kaushiksaliya** [comment]
let's remove country picker dependence.

**Comment by kaushiksaliya** [comment]
Show apple login button in android as well.

**Comment by cp-ishita-g** [comment]
> Show apple login button in android as well.

i am going to create new mr on this, at time i will add this

**Comment by kaushiksaliya** [comment]
> > Show apple login button in android as well.
> 
> i am going to create new mr on this, at time i will add this

no need to create other mr, do in this mr.

**Comment by kaushiksaliya** [comment]
> > Show apple login button in android as well.
> 
> i am going to create new mr on this, at time i will add this

No need to create other mr for this, do in this mr.

**Comment by cp-ishita-g** [comment]
> > > Show apple login button in android as well.
> > 
> > 
> > i am going to create new mr on this, at time i will add this
> 
> No need to create other mr for this, do in this mr.

different task should have different tickets, apple login and removing phone login is different task, so it should be in different mr, and i am going to create new mr for this

**Review by kaushiksaliya — APPROVED** [review]

**Pull request merged**
