### PR TITLE
Verify: Intermediate locations are added for moving journey

### PR DESCRIPTION
**Pull request by cp-ishita-g**
- [x] add location update for moving user in cache
- [x] pass route from cache while saving moving journey
- [x] clear location route from cache while adding steady journey to get new routes from start to end of new journey
- [x] fix showing proper route from where user move from location a -> b

## Summary by CodeRabbit

- **New Features**
	- Enhanced journey management with improved route tracking based on user locations.
	- Added functionality to store and retrieve user-specific location data.
	- Introduced geofencing capabilities for improved location management.
	- Updated location accuracy settings for better performance.
	- Conditional execution for background services based on platform (iOS/Android).

- **Bug Fixes**
	- Streamlined journey saving logic to improve accuracy in route construction.
	- Added checks for location permissions before starting background services.

- **Documentation**
	- Updated documentation to reflect new methods and functionality in the JourneyRepository and LocationCache classes.

### CODE REVIEW

**Review by cp-megh-l — COMMENTED** [review]
I don't think there is need to cache location and clear it everytime....

Previous code should provide you routes list i guess:

```
routes: [
          lastKnownJourney.toPositionFromSteadyJourney().toJourneyRoute(),
          extractedLocation.toJourneyRoute()
        ]
```

**Comment by cp-ishita-g** [comment]
> I don't think there is need to cache location and clear it everytime....
> 
> Previous code should provide you routes list i guess:
> 
> ```
> routes: [
>           lastKnownJourney.toPositionFromSteadyJourney().toJourneyRoute(),
>           extractedLocation.toJourneyRoute()
>         ]
> ```

with this we are not getting the in between location so in map it always stood up straight line between location a -> b, that's why i differently storing all in between location for one  moving journey at a time, so in google map we have more route point which will show exact line from user move

**Comment by cp-megh-l** [comment]
> with this we are not getting the in between location so in map it always stood up straight line between location a -> b, that's why i differently storing all in between location for one moving journey at a time, so in google map we have more route point which will show exact line from user move

@cp-ishita-g That means you guys are resetting routes list some where in code otherwise, logically, it should show routes between 2 destinations!

**Comment by cp-ishita-g** [comment]
> > with this we are not getting the in between location so in map it always stood up straight line between location a -> b, that's why i differently storing all in between location for one moving journey at a time, so in google map we have more route point which will show exact line from user move
> 
> @cp-ishita-g That means you guys are resetting routes list some where in code otherwise, logically, it should show routes between 2 destinations!

we are not resetting it but we are not updating every in between location update in route, it will make to many calls, instead of that i come up with this solution for adding route in journey

**Comment by cp-megh-l** [comment]
> 
> we are not resetting it but we are not updating every in between location update in route, it will make to many calls, instead of that i come up with this solution for adding route in journey

I think there is update journey call for updating `from->to` for moving journey.. then how it will make too many calls?

**Review by kaushiksaliya — APPROVED** [review]

**Pull request merged**
