### PR TITLE
Do not allow to delete group if there are more than 1 member

### PR DESCRIPTION
**Pull request by cp-ishita-g**
- [x] if there are more than 1 member present in group do not allow admin to delete group
- [x] change admin if admin want to leave group
- [x] change icon size for user journey detail screen and journey time line screen

Simulator Screen Recording - iPhone 15 Plus - 2024-12-09 at 12 22 14

## Summary by CodeRabbit

- **New Features**
	- Introduced a new screen for changing group administrators.
	- Added conditional logic for displaying buttons based on user roles in space management.
	- Enhanced localization with new strings for group management and permissions.

- **Bug Fixes**
	- Adjusted marker sizes and appearance based on the platform for better usability.

- **Documentation**
	- Updated localization strings for clearer user instructions and error handling.

- **Chores**
	- Updated dependencies to source the `flutter_slidable` package directly from Git.

### CODE REVIEW

**Comment by kaushiksaliya** [comment]
Fix marker icon size. it is showing very small.


Screenshot from 2024-12-11 18-00-22

**Comment by kaushiksaliya** [comment]
i am not able to join same group again after leave group.

[join_group.webm](https://github.com/user-attachments/assets/4336edf3-0b48-4845-8eb6-9594677305a5)

**Review by kaushiksaliya — APPROVED** [review]

**Comment by kaushiksaliya** [comment]
> Fix marker icon size. it is showing very small.
> 
> Screenshot from 2024-12-11 18-00-22

it is still small.

**Comment by kaushiksaliya** [comment]
Still not proper.

Screenshot from 2024-12-12 10-47-04
Screenshot from 2024-12-12 10-45-57

**Comment by cp-ishita-g** [comment]
> Still not proper. one is bigger and one is smaller.
> 
> Screenshot from 2024-12-12 10-47-04 Screenshot from 2024-12-12 10-45-57

as i am not able to test in android, can you please make change and push code

**Review by kaushiksaliya — APPROVED** [review]

**Pull request merged**
